services:
  rxtrax-frontend:
    container_name: rxtrax-frontend
    image: rxtrax-frontend
    restart: unless-stopped
    depends_on:
      - rxtrax-backend
    ports:
      - "90:80"
    environment:
      - TZ=America/Chicago
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
      - homepage.group=Personal
      - homepage.name=RxTrax
      - homepage.icon=https://rx.postfmly.com/rxtrax.png
      - homepage.href=https://rx.postfmly.com/
      - homepage.description=rx.postfmly.com

  rxtrax-backend:
    container_name: rxtrax-backend
    image: rxtrax-backend
    restart: unless-stopped
    ports:
      - "5556:5556"
    volumes:
      - db:/backend/db
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
    stop_signal: SIGINT

volumes:
  db:

networks: {}

x-dockge:
  urls:
    - https://rx.postfmly.com
